sonar.projectKey=Ani2708_music-web-app
sonar.organization=ani2708
sonar.sources=.

sonar.exclusions=node_modules/**,coverage/**,.scannerwork/**,backend/node_modules/**,**/*.sql

sonar.javascript.node.maxspace=4096
sonar.sourceEncoding=UTF-8